In [ ]:
import numpy as np

In [ ]:
# printing version and configuration 
print(np.__version__)
np.show_config() 

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
# create a null vecor of size 10 
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# How to find memory size of any array
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))
print("z.size = ", z.size)
print('z.itemsize= ',z.itemsize)

800 bytes
z.size =  100
z.itemsize=  8


In [ ]:
# getting documentation of the numpy add function from the command line 
# python -m "import numpy; numpy.info(numpy.add)"

In [ ]:
# create a vector with values ranging from 10 to 49 
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# reversing a vector 
z = np.arange(11)
z = z[::-1]
print(z)

[10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
# create a 3*3 matrix with values ranging from 0 to 8 
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# find indices of non-zero elements from [1,2,0,0,4,0]
z= np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4]),)


In [ ]:
# finding indexes from a numpy array using a condition 
a = [1,2,0,0,4,0] 
b = []
for c in range(0,len(a)):
    if a[c] != 0:
        b.append(c)
print(b)

[0, 1, 4]


In [ ]:
# create a 3*3 identity matrix 
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# creating a zero matrix 
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# creating a 3*3*3 array with random values 
a = np.random.random((3,3,2))
a

array([[[0.43945364, 0.56058869],
        [0.496706  , 0.50913851],
        [0.23248823, 0.23428062]],

       [[0.84581618, 0.79076154],
        [0.67422836, 0.993314  ],
        [0.50935171, 0.54771615]],

       [[0.00671636, 0.93694899],
        [0.93248934, 0.9691757 ],
        [0.99569847, 0.46654791]]])

In [ ]:
# create a 10*10 array with random values and find the minimum and maximum values 
a = np.random.random((10,10))
a_min, a_max = a.min(),a.max()
a_min,a_max

(0.01761627806697974, 0.9755092110902365)

In [ ]:
# create a random vector of size 30 and find the mean value 
a = np.random.random(30) 
m  = a.mean()
print('size - ', a.size)
print('shape-' ,a.shape)
print('dimension-',a.ndim)
print('itemsize -',a.itemsize)

size -  30
shape- (30,)
dimension- 1
itemsize - 8


In [ ]:
# create a 2 d array with 1 on the border and 0 inside 
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
 # How to add a border filled with 0 around an existing array 
a = np.ones((5,5))
a[:,[0,-1]] = 0  # making first and last columns zero 
a[[0,-1],:] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [ ]:
# creating a 5*5 matrix values 1,2,3,4 just below the diagonal 
z = np.diag(1+np.arange(4),k = -1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[::2,::2] = 1
Z[1::2,1::2] = 1
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
# consider a (6,7,8) shape array what is the index (x,y,z) of the 100th element 
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [ ]:
# create a checkerboard 8*8 matrix using the tile function 
z = np.tile([[0,1],[1,0]],(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# normalize  a 5*5 random matrix

np.random.seed(101)
z = np.random.random((5,5))
z = (z-np.mean(z))/np.std(z)
z

array([[ 0.2330826 ,  0.424604  , -1.48885873, -0.9840279 ,  0.82907374],
       [ 1.35357039, -0.50602845,  1.56431579,  0.95706373, -0.91903113],
       [ 0.36658537, -0.34663338, -0.94742834,  1.18313143,  1.81795379],
       [-0.76934475, -1.29444964,  0.54064425,  0.98335174, -0.61446895],
       [ 0.82917731,  0.23826633, -1.41824004, -1.10279115, -0.929518  ]])

In [ ]:
# multiply a 5 *3 matrix by a 3*2 matrix ( real matrix product)
a = np.dot(np.ones((5,3)),np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
# alternate solution 
a = np.ones((5,2)) @ np.ones((2,3))
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
# negating all elements which are between 3 and 8 
a = np.arange(11)
for index in range(0,len(a)):
    if a[index]>=3 and a[index]<=8:
        a[index] =a[index] *(-1)
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
