<a href="https://colab.research.google.com/github/thomasreji155/Python-Notes/blob/main/Copy_of_Numpy_fullNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy UFuncs
Numpy provides a convinient interface for vectorised operations. A simple operation on the array will be then applied to each element. 

This vecotorized approach is designed to push the loop in to the compiled layer and leading to faster excecution

vectorized operations in numpy are implemented via ufuncs, whose main purpose is to quikly excecute repeated operations on values in Numpy arrays. Using this we can also operate between 2 layers also. 

# loading the library

In [ ]:
import numpy as np

In [ ]:
np.arange(5),np.arange(1,6)

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

In [ ]:
g = np.arange(5)/ np.arange(1,6)
g

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
x = np.arange(9).reshape((3,3))
o = 2*x
o

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
o//2        # floor division 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.pi

3.141592653589793

In [ ]:
v =np.array([2,3,5,6])
np.add(v,np.array([4,2,6,3]))    # shapes should be equal this is element wise addition

array([ 6,  5, 11,  9])

In [ ]:
abs(v)   # return the absolute value
np.abs(v)
np.absolute(v)

array([2, 3, 5, 6])

In [ ]:
# trigonometric functions 
alpha = np.linspace(1,11,5)
print(alpha)
print('sin alpha = ',np.sin(alpha))
print('arcsin alpha = ',np.arcsin(alpha)) 
print('exp alpha = ',np.exp(alpha))
print('alpha power2 = ', np.exp2(alpha))
print('alpha power 3 = ',np.power(3,alpha))
print('log alpha',np.log(alpha))
print('log2 of alpha',np.log2(alpha))
print('log10 of alpha',np.log10(alpha)) 

[ 1.   3.5  6.   8.5 11. ]
sin alpha =  [ 0.84147098 -0.35078323 -0.2794155   0.79848711 -0.99999021]
arcsin alpha =  [1.57079633        nan        nan        nan        nan]
exp alpha =  [2.71828183e+00 3.31154520e+01 4.03428793e+02 4.91476884e+03
 5.98741417e+04]
alpha power2 =  [2.00000000e+00 1.13137085e+01 6.40000000e+01 3.62038672e+02
 2.04800000e+03]
alpha power 3 =  [3.00000000e+00 4.67653718e+01 7.29000000e+02 1.13639853e+04
 1.77147000e+05]
log alpha [0.         1.25276297 1.79175947 2.14006616 2.39789527]
log2 of alpha [0.         1.80735492 2.5849625  3.08746284 3.45943162]
log10 of alpha [0.         0.54406804 0.77815125 0.92941893 1.04139269]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in arcsin
  """


In [ ]:
x=np.arange(1,6)
np.add.reduce(x) 

15

In [ ]:
np.multiply.reduce(x)

120

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
x=np.array([1,6,1,2,3])
x[[0,2]]
x[[0,2]]

np.multiply.outer(x,x)         
# first column x multiplied with the 5 
# second column x multiplied with the 2 ...

array([[ 1,  6,  1,  2,  3],
       [ 6, 36,  6, 12, 18],
       [ 1,  6,  1,  2,  3],
       [ 2, 12,  2,  4,  6],
       [ 3, 18,  3,  6,  9]])

In [ ]:
x=np.arange(1,6)
np.add.outer(x,x)  
# first column adding 1 to x 
# second column adding 2 to x ... 

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [ ]:
x = np.array([1,3,2])
np.subtract.outer(x,x)

array([[ 0, -2, -1],
       [ 2,  0,  1],
       [ 1, -1,  0]])

# Aggregation 

In [ ]:
data = np.random.random(100)
print('sum', np.sum(data))
print('min', np.min(data))
print('max',np.max(data))

sum 47.745136190536144
min 0.010160147569287514
max 0.9825352809706249


In [ ]:
# checking whether any value is greater than 1
np.any(data>1)

False

In [ ]:
# checking whther all the values are greater than  0
np.all(data >0) 

True

In [ ]:
# another way of method calling 
print(data.min())
print(data.max())
print(data.std())

print(data.sum())
print(data.var())
print(data.prod())

print(data.mean())

0.010160147569287514
0.9825352809706249
0.29832655199458974
47.745136190536144
0.08899873162498066
4.382145884178857e-48
0.4774513619053614


In [ ]:
y = np.arange(5,10)
g = np.add.outer(y,y)
g

array([[10, 11, 12, 13, 14],
       [11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16],
       [13, 14, 15, 16, 17],
       [14, 15, 16, 17, 18]])

In [ ]:
f = np.random.random(15)
f.shape

(15,)

In [ ]:
f.reshape(15,1)   # reshaping 

array([[0.14448756],
       [0.91431818],
       [0.98388106],
       [0.01446453],
       [0.41979604],
       [0.6172476 ],
       [0.18724133],
       [0.7735466 ],
       [0.5512903 ],
       [0.41844797],
       [0.11726777],
       [0.88752641],
       [0.69775684],
       [0.48904376],
       [0.38967473]])

In [ ]:
f = f.reshape(3,5)
f

array([[0.14448756, 0.91431818, 0.98388106, 0.01446453, 0.41979604],
       [0.6172476 , 0.18724133, 0.7735466 , 0.5512903 , 0.41844797],
       [0.11726777, 0.88752641, 0.69775684, 0.48904376, 0.38967473]])

In [ ]:
# finding aggregate based on axis
f.min(axis = 0) # based on columns 

array([0.11726777, 0.18724133, 0.69775684, 0.01446453, 0.38967473])

In [ ]:
f.min(axis = 1) # based on rows 

array([0.01446453, 0.18724133, 0.11726777])

In [ ]:
f.argmin(axis = 0)     # getting the indexes of min values across columns

array([2, 1, 2, 0, 2])

In [ ]:
# from google.colab import files
# files.upload()

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_test.csv') 

In [ ]:
df   # Housing data 

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [ ]:
df_array = np.array(df,dtype = 'float32')

In [ ]:
price_col = df_array[:,-1]    # here -1 refers to last column

In [ ]:
price_col

array([344700., 176500., 270500., ...,  62000., 162500., 500001.],
      dtype=float32)

In [ ]:
print(type(price_col))     # Now it is numpy array

<class 'numpy.ndarray'>


In [ ]:
df_array.shape

(3000, 9)

In [ ]:
price_col.mean()       # finding mean of price 

205846.27

In [ ]:
price_col.std()         # finding standard deviation of price 

113100.836

In [ ]:
df_array[:,[0,1]]   # slicing longitude and latitude 

array([[-122.05,   37.37],
       [-118.3 ,   34.26],
       [-117.81,   33.78],
       ...,
       [-119.7 ,   36.3 ],
       [-117.12,   34.1 ],
       [-119.63,   34.42]], dtype=float32)

In [ ]:
df_array[:,[0,1]][df_array[:,1] < 34 ]    
# filtering latitude based on longitude < 34   

array([[-117.81,   33.78],
       [-118.36,   33.82],
       [-118.24,   33.98],
       ...,
       [-118.25,   33.93],
       [-117.91,   33.6 ],
       [-117.93,   33.86]], dtype=float32)

In [ ]:
print("25th percentile",np.percentile(price_col,25))
print("Median",np.median(price_col))
print("75th percentile",np.percentile(price_col,75))

25th percentile 121200.0
Median 177650.0
75th percentile 263975.0


# Numpy Broadcasting 

Another means of vectorizing operation is to use Numpy's broadcasting functionality. Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication) on arrays of different sizes.

In [ ]:
a = np.arange(3)
b = np.random.randint(0,4,3)    # 3 random numbers between 0 and 4 (excluded)

In [ ]:
print(a)
print(b)
print(a+b)

[0 1 2]
[1 3 1]
[1 4 3]


In [ ]:
h = np.ones((3,5))

In [ ]:
h+4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
a = np.arange(0,5)
print(a)
print(a.shape)   # this is one dimensional array 

[0 1 2 3 4]
(5,)


In [ ]:
# converting a to a column or raw vector we apply np.newaxis method
a_new = a[:,np.newaxis ]
print(a_new)
print(a_new.shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

# Comparison Operators as Ufuncs

In [ ]:
s = np.array([1,2,3,5,2])
s<3

array([ True,  True, False, False,  True])

In [ ]:
# finding the index of array element where it is True
np.argwhere(s<3)

array([[0],
       [1],
       [4]])

In [ ]:
# finding count of distict elements in an array
x = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x, return_counts=True) 
unique,counts

(array([ 1,  2,  5, 25]), array([5, 3, 1, 1]))

In [ ]:
np.asarray((unique,counts)).T

array([[ 1,  5],
       [ 2,  3],
       [ 5,  1],
       [25,  1]])

In [ ]:
print(x)
print(np.not_equal(x,3))

[ 1  1  1  2  2  2  5 25  1  1]
[ True  True  True  True  True  True  True  True  True  True]


In [ ]:
print(x)
print(np.equal(x,3))

[ 1  1  1  2  2  2  5 25  1  1]
[False False False False False False False False False False]


In [ ]:
print(x)
print(np.less(x,3))

[ 1  1  1  2  2  2  5 25  1  1]
[ True  True  True  True  True  True False False  True  True]


In [ ]:
print(x)
print(np.greater(x,3))

[ 1  1  1  2  2  2  5 25  1  1]
[False False False False False False  True  True False False]


In [ ]:
np.greater_equal(x,3)

array([False, False, False, False, False, False,  True,  True, False,
       False])

In [ ]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [ ]:
np.count_nonzero(x<6) # how many values less than 6

8

In [ ]:
np.any(x>8)  #are there any values greater than 8

True

In [ ]:
np.all(x<10)    # all values less than 10?

True

In [ ]:
np.all(x<8,axis=1)   #are all values in each row less than 8

array([ True, False,  True])

In [ ]:
import seaborn as sns
train=sns.load_dataset('iris')
sepal=np.array(train['sepal_length']) 
pet = np.array(train['petal_width']) 
np.sum((sepal >4.7)  & (pet!=1.5))  

127

# Splitting of Arrays

In [ ]:
x = [1,2,3,4,65,34,21,32]
x1,x2,x3 = np.split(x,[3,6])   # 6 is excluded

In [ ]:
x1 ,x2,x3

(array([1, 2, 3]), array([ 4, 65, 34]), array([21, 32]))

In [ ]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper,lower = np.vsplit(grid,[2])

In [ ]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
z=[99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [ ]:
grid=np.array([[1,2,3],
              [4,5,6]])

# Concatenation

In [ ]:
np.concatenate([grid,grid]) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
              [6,5,4]])

In [ ]:
x.shape

(3,)

In [ ]:
grid.shape

(2, 3)

In [ ]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
y = np.array([1,2])
y = y[np.newaxis,:].T
y

array([[1],
       [2]])

In [ ]:
np.hstack([grid,y])

array([[9, 8, 7, 1],
       [6, 5, 4, 2]])

# Dimensions and size of array

In [ ]:
x1=np.random.randint(10,size=6)   #one dimensional array
x2=np.random.randint(10,size=(3,4))  #two dimensional array
x3=np.random.randint(10,size=(3,4,5))  #three dimensional array

In [ ]:
print("x3 ndim",x3.ndim)     #number of dimensions
print("x3 shape",x3.shape)   #exact value of dimension
print("x3 size",x3.size)     #total number of elements
print("dtype",x3.dtype)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60
dtype int64


In [ ]:
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
#create a 3X3 array of normally distributed random values 
#with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3)) 

array([[-1.32559502,  0.77171446, -0.83631625],
       [ 0.1357142 , -0.0991595 , -0.33713325],
       [-1.2034266 , -0.5426326 , -1.04462789]])

In [ ]:
#create a 3X3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[7, 1, 0],
       [1, 7, 3],
       [2, 5, 4]])

In [ ]:
#create a 3X3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create an uninitialized array of 3 integrs
np.empty(3)

array([1., 1., 1.])

In [ ]:
#create a 3X5 floating-point array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
#create a 3X5 floating-point array filled with 1's
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#creating a length 10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# creating array using python list 
np.array([range (i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# giving datatype while creating array
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
import array
L=list(range(10))
A=array.array('i',L)

# Create structured Arrays

In [ ]:
np.dtype({'names':('name','age','weight'),'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [ ]:
np.dtype([('name','S10'),('age','i4'),('weight','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [ ]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])

In [ ]:
X=np.zeros(1,dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# sorting and structured array

In [ ]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
print(x) 

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [ ]:
np.sort(x,axis = 0)   # axis= 0 means column in numpy 

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [ ]:
np.sort(x, axis= 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [ ]:
np.partition(x,4,axis = 1)

array([[6, 6, 3, 4, 7, 9],
       [3, 2, 6, 4, 7, 7],
       [1, 5, 2, 4, 7, 7],
       [0, 4, 1, 5, 5, 9]])

# Moddifying value with fancy indexing 

In [ ]:
# fancy indexing means passing of array of indices to access multiple
# array elements at once. 

In [ ]:
np.random.RandomState(42) 
import random as rand
x = np.random.randint(100, size = 10)
x

array([70,  0, 71, 36, 14, 24, 44, 90,  0, 26])

In [ ]:
indeces = [3,2,1,0]
x[indeces]

array([36, 71,  0, 70])

In [ ]:
x = np.arange(12).reshape((3,4)) 
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row = [0,1,2]
cols = [2,1,3]
x[row,cols]

array([ 2,  5, 11])

In [ ]:
x = np.random.randint(100,size = 10)
ind = np.array([[2,3,1],
                [4,1,2]])
print(x)
x[ind] 

[84 37  1 28 97 48 11 79 46  6]


array([[ 1, 28, 37],
       [97, 37,  1]])

In [ ]:
x = np.random.randint(12,size = (3,4))
print(x)
row = np.array([0,1,2])
col = np.array([2,1,3])
print()
print(x[row,col])
newarr = row[:,np.newaxis]
print()
print(newarr)
print()
x[newarr,col]

[[ 8  7  3  7]
 [ 4 11  3  8]
 [10  1  0  6]]

[ 3 11  6]

[[0]
 [1]
 [2]]



array([[ 3,  7,  7],
       [ 3, 11,  8],
       [ 0,  1,  6]])

In [ ]:
# combined indexing 
x

array([[ 8,  7,  3,  7],
       [ 4, 11,  3,  8],
       [10,  1,  0,  6]])

In [ ]:
x[1:,[3,1]]  # combine fancy indexing with indexing and slicing 

array([[ 8, 11],
       [ 6,  1]])

In [ ]:
x[2,[2,0,1]]   # 

array([ 0, 10,  1])

In [ ]:
# combine fancy indexing with masking 
mask=np.array([1,0,1,0],dtype=bool)
print('mask',mask)
print('x',x)
print('row', row)
x[row[:,np.newaxis],mask]

mask [ True False  True False]
x [[ 8  7  3  7]
 [ 4 11  3  8]
 [10  1  0  6]]
row [0 1 2]


array([[ 8,  3],
       [ 4,  3],
       [10,  0]])

# Array slicing 

In [ ]:
import numpy as np
m1 = np.random.randint(10,size = (4,3)) 
m2 = np.arange(13,22)

In [ ]:
m1

array([[3, 3, 6],
       [3, 7, 8],
       [2, 1, 1],
       [1, 6, 0]])

In [ ]:
m2

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [ ]:
m2[::-1]              # in order to reverse the array

array([21, 20, 19, 18, 17, 16, 15, 14, 13])

In [ ]:
m2[::2]              # jump with step size of 2

array([13, 15, 17, 19, 21])

In [ ]:
m2[3]               # taking the third element 

16

In [ ]:
m2[3:5]            # printing third and forth element 

array([16, 17])

In [ ]:
m2

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [ ]:
m2[::-2]

array([21, 19, 17, 15, 13])

In [ ]:
m1

array([[3, 3, 6],
       [3, 7, 8],
       [2, 1, 1],
       [1, 6, 0]])

In [ ]:
m1[:2,:3] 

array([[3, 3, 6],
       [3, 7, 8]])

In [ ]:
m1[:,::-2]

array([[6, 3],
       [8, 3],
       [1, 2],
       [0, 1]])

In [ ]:
m1[::-1,::-1]

array([[0, 6, 1],
       [1, 1, 2],
       [8, 7, 3],
       [6, 3, 3]])

In [ ]:
m1[0]    # first row 

array([3, 3, 6])

In [ ]:
m1[:,0]      # first column

array([3, 3, 2, 1])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[4, 9, 3],
       [2, 6, 6],
       [3, 7, 4]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 2.23209227,  2.64061942, -0.72569752],
       [-0.11747029, -0.09039575,  0.52005619],
       [ 1.30931906,  0.97440237,  1.780817  ]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])