In [213]:
import pandas as pd 
import os 
import matplotlib.pyplot as plt 
%matplotlib inline 
import numpy as np 

In [307]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [215]:
titanic_train.tail(5)

PassengerId  Survived  Pclass                               Name     Sex  \
151          152         1       1  Pears, Mrs. Thomas (Edith Wearne)  female   
152          153         0       3                   Meo, Mr. Alfonzo    male   
153          154         0       3    van Billiard, Mr. Austin Blyler    male   
154          155         0       3              Olsen, Mr. Ole Martin    male   
155          156         0       1        Williams, Mr. Charles Duane    male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
151  22.0      1      0      113776  66.6000    C2        S  
152  55.5      0      0  A.5. 11206   8.0500   NaN        S  
153  40.5      0      2    A/5. 851  14.5000   NaN        S  
154   NaN      0      0   Fa 265302   7.3125   NaN        S  
155  51.0      0      1    PC 17597  61.3792   NaN        C

In [308]:
df = titanic_train

In [217]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [218]:
df.dtypes == "object" 

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [219]:
a = df.dtypes[df.dtypes == 'object'].index
a


Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [220]:
df[a].describe()

Name   Sex Ticket        Cabin Embarked
count                 156   156    156           31      155
unique                156     2    145           28        3
top     Rugg, Miss. Emily  male   2651  C23 C25 C27        S
freq                    1   100      2            2      110

In [221]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [222]:
df.dtypes[df.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [223]:
object_columns = df.dtypes[df.dtypes == "object"].index 
df[object_columns]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female   
152                                   Meo, Mr. Alfonzo    male   
153                    van Billiard, Mr. Austin Blyler    male   
154                              Olsen, Mr. Ole Martin    male   
155                        Williams, Mr. Charles Duane    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
151            113776    C2        S  
152        A.5. 11206   NaN        S  
153          A/5. 851   NaN        S  
154         Fa 265302   NaN        S  
155          PC 17597   NaN        C  

[156 rows x 5 columns]

In [224]:
df[['Name', 'Age', 'Cabin']]

Name   Age Cabin
0                              Braund, Mr. Owen Harris  22.0   NaN
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0   C85
2                               Heikkinen, Miss. Laina  26.0   NaN
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  C123
4                             Allen, Mr. William Henry  35.0   NaN
..                                                 ...   ...   ...
151                  Pears, Mrs. Thomas (Edith Wearne)  22.0    C2
152                                   Meo, Mr. Alfonzo  55.5   NaN
153                    van Billiard, Mr. Austin Blyler  40.5   NaN
154                              Olsen, Mr. Ole Martin   NaN   NaN
155                        Williams, Mr. Charles Duane  51.0   NaN

[156 rows x 3 columns]

In [225]:
sorted(df["Name"])[1:10]

['Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [226]:
sorted(df["Name"], reverse= True)[1: 5]

['Zabour, Miss. Hileni',
 'Woolner, Mr. Hugh',
 'Williams, Mr. Charles Eugene',
 'Williams, Mr. Charles Duane']

In [227]:
df['Name'].describe()

count                   156
unique                  156
top       Rugg, Miss. Emily
freq                      1
Name: Name, dtype: object

In [228]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [229]:
df['newcol'] = "missing"

In [230]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked   newcol  
0      0         A/5 21171   7.2500   NaN        S  missing  
1      0          PC 17599  71.2833   C85        C  missing  
2      0  STON/O2. 3101282   7.9250   NaN        S  missing

In [231]:
df[["Name"]] # this is not a series but a dataframe 

Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
151                  Pears, Mrs. Thomas (Edith Wearne)
152                                   Meo, Mr. Alfonzo
153                    van Billiard, Mr. Austin Blyler
154                              Olsen, Mr. Ole Martin
155                        Williams, Mr. Charles Duane

[156 rows x 1 columns]

In [232]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
newcol          object
dtype: object

In [233]:
new_survivied = pd.Categorical(df['Survived'])
new_survivied

[0, 1, 1, 1, 0, ..., 1, 0, 0, 0, 0]
Length: 156
Categories (2, int64): [0, 1]

In [234]:
df['Survived'].unique()

array([0, 1])

In [235]:
df[['Cabin']]

Cabin
0     NaN
1     C85
2     NaN
3    C123
4     NaN
..    ...
151    C2
152   NaN
153   NaN
154   NaN
155   NaN

[156 rows x 1 columns]

In [236]:
character_cab = df['Cabin'].astype(str)
new_cabin = [char[0] for char in character_cab] 

In [237]:
new_cabin = pd.Categorical(new_cabin)

In [238]:
df['newc'] = new_cabin

In [239]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked   newcol newc  
0      0         A/5 21171   7.2500   NaN        S  missing    n  
1      0          PC 17599  71.2833   C85        C  missing    C  
2      0  STON/O2. 3101282   7.9250   NaN        S  missing    n

In [240]:
titanic_train.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked   newcol newc  
0      0         A/5 21171   7.2500   NaN        S  missing    n  
1      0          PC 17599  71.2833   C85        C  missing    C  
2      0  STON/O2. 3101282   7.9250   NaN        S  missing    n

In [241]:
df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
151        False     False   False  False  False  False  False  False   False   
152        False     False   False  False  False  False  False  False   False   
153        False     False   False  False  False  False  False  False   False   
154        False     False   False  False  False   True  False  False   False   
155        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  newcol   newc  
0    False   True     False   False  False  
1    False  False     False   False  False  
2    False   True     False   False  False  
3    False  False     False   False  False  
4    False   True     False   False  False  
..     ...    ...       ...     ...    ...  
151  False  False     False   False  False  
152  False   True     False   False  False  
153  False   True     False   False  False  
154  False   True     False   False  False  
155  False   True     False   False  False  

[156 rows x 14 columns]

In [242]:
np.where(df['Fare'] == max(df['Fare'])) 

(array([27, 88]),)

In [243]:
df['SibSp']

0      1
1      1
2      0
3      1
4      0
      ..
151    1
152    0
153    0
154    0
155    0
Name: SibSp, Length: 156, dtype: int64

In [244]:
df['Parch']

0      0
1      0
2      0
3      0
4      0
      ..
151    0
152    0
153    2
154    0
155    1
Name: Parch, Length: 156, dtype: int64

In [245]:
df['Family']  = df['SibSp'] + df["Parch"]

In [246]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked   newcol newc  Family  
0      0  A/5 21171   7.2500   NaN        S  missing    n       1  
1      0   PC 17599  71.2833   C85        C  missing    C       1

In [247]:
most_family = np.where(df.Family == max(df.Family))

In [248]:
most_family

(array([59, 71]),)

In [249]:
df.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked   newcol newc  Family  
59  11.0      5      2  CA 2144  46.9   NaN        S  missing    n       7  
71  16.0      5      2  CA 2144  46.9   NaN        S  missing    n       7

In [250]:
labels = ['a', 'b','c'] 
my_data = [10,12, 24] 
arr = np.array(my_data)
d = {'a':10, 'b':12, 'c':24} 
print("labels", labels) 
print("my_data" , my_data) 
print("dictionary", d ) 
print(arr)
pd.Series(my_data, index = labels)

labels ['a', 'b', 'c']
my_data [10, 12, 24]
dictionary {'a': 10, 'b': 12, 'c': 24}
[10 12 24]


a    10
b    12
c    24
dtype: int64

In [251]:
print(pd.Series(arr)[1])

12


In [252]:
#  a print statement 
print("thomaskutty", '-'*25, sep = "\n")

thomaskutty
-------------------------


In [253]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [254]:
pd.Series(my_data)

0    10
1    12
2    24
dtype: int64

In [255]:
ser = pd.Series(my_data, index = labels)
ser

a    10
b    12
c    24
dtype: int64

In [256]:
d = {'a': "thomas", 'b': 25, 'c':23} 
print(d)

{'a': 'thomas', 'b': 25, 'c': 23}


In [257]:
d.items()

dict_items([('a', 'thomas'), ('b', 25), ('c', 23)])

In [258]:
pd.DataFrame(d, index = 
             [i for i in range(len(d.keys()))])

a   b   c
0  thomas  25  23
1  thomas  25  23
2  thomas  25  23

In [259]:
pd.DataFrame(d, index = [i for i in d.keys()])

a   b   c
a  thomas  25  23
b  thomas  25  23
c  thomas  25  23

In [260]:
print(type)
print(sum)
print(max)

<class 'type'>
<built-in function sum>
<built-in function max>


In [261]:
pd.Series([type, sum, max])

0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object

In [262]:
ser1 = pd.Series([1,2,2,4], index = ['a', 'b', 'c', 'd'])
ser1

a    1
b    2
c    2
d    4
dtype: int64

In [263]:
ser2 = pd.Series([23,13,235,23], ['id_2', 'non', 'd', 'sdf'])
ser2

id_2     23
non      13
d       235
sdf      23
dtype: int64

In [264]:
df.describe(include = 'all') 
# getting the description of both categorical and numerical features

PassengerId    Survived      Pclass               Name   Sex  \
count    156.000000  156.000000  156.000000                156   156   
unique          NaN         NaN         NaN                156     2   
top             NaN         NaN         NaN  Rugg, Miss. Emily  male   
freq            NaN         NaN         NaN                  1   100   
mean      78.500000    0.346154    2.423077                NaN   NaN   
std       45.177428    0.477275    0.795459                NaN   NaN   
min        1.000000    0.000000    1.000000                NaN   NaN   
25%       39.750000    0.000000    2.000000                NaN   NaN   
50%       78.500000    0.000000    3.000000                NaN   NaN   
75%      117.250000    1.000000    3.000000                NaN   NaN   
max      156.000000    1.000000    3.000000                NaN   NaN   

               Age       SibSp       Parch Ticket        Fare        Cabin  \
count   126.000000  156.000000  156.000000    156  156.000000           31   
unique         NaN         NaN         NaN    145         NaN           28   
top            NaN         NaN         NaN   2651         NaN  C23 C25 C27   
freq           NaN         NaN         NaN      2         NaN            2   
mean     28.141508    0.615385    0.397436    NaN   28.109587          NaN   
std      14.613880    1.056235    0.870146    NaN   39.401047          NaN   
min       0.830000    0.000000    0.000000    NaN    6.750000          NaN   
25%      19.000000    0.000000    0.000000    NaN    8.003150          NaN   
50%      26.000000    0.000000    0.000000    NaN   14.454200          NaN   
75%      35.000000    1.000000    0.000000    NaN   30.371850          NaN   
max      71.000000    5.000000    5.000000    NaN  263.000000          NaN   

       Embarked   newcol newc      Family  
count       155      156  156  156.000000  
unique        3        1    8         NaN  
top           S  missing    n         NaN  
freq        110      156  125         NaN  
mean        NaN      NaN  NaN    1.012821  
std         NaN      NaN  NaN    1.614400  
min         NaN      NaN  NaN    0.000000  
25%         NaN      NaN  NaN    0.000000  
50%         NaN      NaN  NaN    0.000000  
75%         NaN      NaN  NaN    1.000000  
max         NaN      NaN  NaN    7.000000

In [265]:
ser2[ser2.index == 'id_2']    # filetering the series 

id_2    23
dtype: int64

In [266]:
ser2['id_2']  # accessing elemets using index label

23

In [267]:
ser2[['id_2', 'd']]   # accessing using multiple index labels 

id_2     23
d       235
dtype: int64

In [268]:
ser1

a    1
b    2
c    2
d    4
dtype: int64

In [269]:
ser2

id_2     23
non      13
d       235
sdf      23
dtype: int64

In [270]:
ser1+ ser2 # index wise addition 

a         NaN
b         NaN
c         NaN
d       239.0
id_2      NaN
non       NaN
sdf       NaN
dtype: float64

In [271]:
from numpy.random import randn as rn
import random 
random.seed(23)
matrix_data = rn(5,4) 
matrix_data

array([[-0.6993852 ,  1.72616583, -0.35848391,  1.59823497],
       [ 0.60644021, -1.1455652 ,  0.10349457, -0.34795519],
       [-0.06851477, -1.12932545, -1.41250368, -1.410269  ],
       [-0.80113076,  0.1516981 ,  0.11559998, -1.55517569],
       [ 0.54672132, -0.21423986,  0.2317108 ,  1.0151379 ]])

In [272]:
row_labels = ['a', 'b', 'c', 'd', 'e']
column_heading = ['f1', 'f2', 'f3', 'f4']

In [273]:
newdf = pd.DataFrame(matrix_data, index = row_labels, 
                     columns = column_heading) 
newdf

f1        f2        f3        f4
a -0.699385  1.726166 -0.358484  1.598235
b  0.606440 -1.145565  0.103495 -0.347955
c -0.068515 -1.129325 -1.412504 -1.410269
d -0.801131  0.151698  0.115600 -1.555176
e  0.546721 -0.214240  0.231711  1.015138

In [274]:
# generating column names 
cols = [f'f{i}' for i in range(4)] 
cols

['f0', 'f1', 'f2', 'f3']

In [275]:
newdf

f1        f2        f3        f4
a -0.699385  1.726166 -0.358484  1.598235
b  0.606440 -1.145565  0.103495 -0.347955
c -0.068515 -1.129325 -1.412504 -1.410269
d -0.801131  0.151698  0.115600 -1.555176
e  0.546721 -0.214240  0.231711  1.015138

In [276]:
newdf.iloc[2]

f1   -0.068515
f2   -1.129325
f3   -1.412504
f4   -1.410269
Name: c, dtype: float64

In [277]:
# ordering categorical value 
pd.Categorical(['good' ,'bad' ,'vgood', 'vbad'],
              categories= ['vgood', 'good', 'bad', 'vbad'][::-1] ,
               ordered= True)

['good', 'bad', 'vgood', 'vbad']
Categories (4, object): ['vbad' < 'bad' < 'good' < 'vgood']

In [278]:
df['Survived'].value_counts()

0    102
1     54
Name: Survived, dtype: int64

In [279]:
newdf['f1']

a   -0.699385
b    0.606440
c   -0.068515
d   -0.801131
e    0.546721
Name: f1, dtype: float64

In [280]:
newdf.f1

a   -0.699385
b    0.606440
c   -0.068515
d   -0.801131
e    0.546721
Name: f1, dtype: float64

In [281]:
newdf['New']  = newdf['f1']+newdf['f2'] 
newdf

f1        f2        f3        f4       New
a -0.699385  1.726166 -0.358484  1.598235  1.026781
b  0.606440 -1.145565  0.103495 -0.347955 -0.539125
c -0.068515 -1.129325 -1.412504 -1.410269 -1.197840
d -0.801131  0.151698  0.115600 -1.555176 -0.649433
e  0.546721 -0.214240  0.231711  1.015138  0.332481

In [282]:
newdf.drop('f1', axis = 1, inplace = True)

In [283]:
newdf

f2        f3        f4       New
a  1.726166 -0.358484  1.598235  1.026781
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840
d  0.151698  0.115600 -1.555176 -0.649433
e -0.214240  0.231711  1.015138  0.332481

In [284]:
newdf.drop('f2', axis = 1) 

f3        f4       New
a -0.358484  1.598235  1.026781
b  0.103495 -0.347955 -0.539125
c -1.412504 -1.410269 -1.197840
d  0.115600 -1.555176 -0.649433
e  0.231711  1.015138  0.332481

In [285]:
newdf

f2        f3        f4       New
a  1.726166 -0.358484  1.598235  1.026781
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840
d  0.151698  0.115600 -1.555176 -0.649433
e -0.214240  0.231711  1.015138  0.332481

In [286]:
newdf.drop('a')

f2        f3        f4       New
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840
d  0.151698  0.115600 -1.555176 -0.649433
e -0.214240  0.231711  1.015138  0.332481

In [287]:
newdf

f2        f3        f4       New
a  1.726166 -0.358484  1.598235  1.026781
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840
d  0.151698  0.115600 -1.555176 -0.649433
e -0.214240  0.231711  1.015138  0.332481

In [288]:
newdf.drop('a', inplace = True)

In [289]:
newdf

f2        f3        f4       New
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840
d  0.151698  0.115600 -1.555176 -0.649433
e -0.214240  0.231711  1.015138  0.332481

In [290]:
newdf.iloc[[0,1]]

f2        f3        f4       New
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840

In [291]:
newdf.loc[['b', 'c']]

f2        f3        f4       New
b -1.145565  0.103495 -0.347955 -0.539125
c -1.129325 -1.412504 -1.410269 -1.197840

In [292]:
# selecting columns and rows in the data frame 
newdf.loc[['b', 'c'], ['f3', 'f4']]

f3        f4
b  0.103495 -0.347955
c -1.412504 -1.410269

In [293]:
newdf.iloc[[0,1], [2, 3]]

f4       New
b -0.347955 -0.539125
c -1.410269 -1.197840

In [294]:
[1,2,3,4].__len__()

4

In [298]:
df.notnull().head()

PassengerId  Survived  Pclass  Name   Sex   Age  SibSp  Parch  Ticket  \
0         True      True    True  True  True  True   True   True    True   
1         True      True    True  True  True  True   True   True    True   
2         True      True    True  True  True  True   True   True    True   
3         True      True    True  True  True  True   True   True    True   
4         True      True    True  True  True  True   True   True    True   

   Fare  Cabin  Embarked  newcol  newc  Family  
0  True  False      True    True  True    True  
1  True   True      True    True  True    True  
2  True  False      True    True  True    True  
3  True   True      True    True  True    True  
4  True  False      True    True  True    True

In [300]:
newdf>0

f2     f3     f4    New
b  False   True  False  False
c  False  False  False  False
d   True   True  False  False
e  False   True   True   True

In [301]:
newdf[newdf>0]

f2        f3        f4       New
b       NaN  0.103495       NaN       NaN
c       NaN       NaN       NaN       NaN
d  0.151698  0.115600       NaN       NaN
e       NaN  0.231711  1.015138  0.332481

#### matrix data 

In [302]:
matrix_data = np.matrix('12,23,14; 13,34,23; 45,234,52;23,13,53')

In [303]:
matrix_data

matrix([[ 12,  23,  14],
        [ 13,  34,  23],
        [ 45, 234,  52],
        [ 23,  13,  53]])

In [309]:
row_labels = ['A', 'B', 'C', 'D'] 
column_labels = ['age', 'height', 'weight']  
df1 = pd.DataFrame(matrix_data , index = row_labels, columns = column_labels)

In [310]:
df1

age  height  weight
A   12      23      14
B   13      34      23
C   45     234      52
D   23      13      53

In [312]:
df1[df1['age'] > 13] 

age  height  weight
C   45     234      52
D   23      13      53

In [313]:
df1['weight'] > 50 

A    False
B    False
C     True
D     True
Name: weight, dtype: bool

In [315]:
df1[df1['weight'] > 50]

age  height  weight
C   45     234      52
D   23      13      53

In [325]:
df1[(df1['age'] > 40) & (df1['weight'] > 50)]

age  height  weight
C   45     234      52

In [326]:

matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']

df = pd.DataFrame(data = matrix_data, index = row_labels,
                 columns = column_headings)

In [327]:
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [330]:
df.reset_index()  # not an inplace operation 

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [331]:
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [332]:
df.reset_index(drop = True)

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

In [334]:
df['Profession'] = 'Student Teacher Engineer Doctor Nurse'.split()

In [335]:
df

Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse

In [338]:
df.set_index('Profession') # not an inplace operation 

Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

In [339]:
df

Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse

## multiindexing and index levels 

In [340]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

In [341]:
hier_index = list(zip(outside,inside))

In [342]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [343]:
hier_index = pd.MultiIndex.from_tuples(hier_index) 
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [344]:
type(hier_index)

pandas.core.indexes.multi.MultiIndex

In [346]:
df1 = pd.DataFrame(data = np.round(rn(6,3)),
                  index= hier_index, columns = ['a', 'b' , 'c']) 

In [347]:
df1

a    b    c
G1 1  1.0 -1.0  0.0
   2 -1.0  0.0 -0.0
   3 -1.0  0.0 -1.0
G2 1 -0.0 -0.0 -1.0
   2 -2.0  0.0 -2.0
   3  1.0  1.0  0.0

In [356]:
df1['a']['G1']

1    1.0
2   -1.0
3   -1.0
Name: a, dtype: float64

In [361]:
df1.xs('G2')

a    b    c
1 -0.0 -0.0 -1.0
2 -2.0  0.0 -2.0
3  1.0  1.0  0.0

In [362]:
df1.xs('G1')

a    b    c
1  1.0 -1.0  0.0
2 -1.0  0.0 -0.0
3 -1.0  0.0 -1.0

In [368]:
df1.xs('G1')['c']

1    0.0
2   -0.0
3   -1.0
Name: c, dtype: float64